### ISSUE TITLE
com.devicehive.model.JsonStringWrapper is not mapped as an embeddable

### ISSUE THREAD

**Issue by buryndin** [devicehive/devicehive-java#12]
Description:  com.devicehive.model.JsonStringWrapper is not mapped as an embeddable
Resource:  AccessKeyPermission.java
Path: /server/src/main/java/com/devicehive/model
Location: line 58
Type:  JPA Problem

**Comment by tmatvienko** [comment]
Not an issue in 2.0.0 version
